name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "ci/requirements-dev.txt"

      - run: python -m pip install --upgrade pip
      - run: |
          if [ -f ci/requirements-dev.txt ]; then
            pip install -r ci/requirements-dev.txt
          fi

      - name: Build (sdist+wheel) if project is packageable
        run: |
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m build
          else
            echo "No packaging config found; skipping build"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI (Trusted Publisher)
        if: ${{ hashFiles('pyproject.toml') != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
